set dotenv-load := true

install:
    uv sync

dev:
    uvicorn src.app.main:app --reload --host 0.0.0.0 --port 8000

format:
    ruff format .

lint:
    ruff check .

clean:
    rm -rf dist
    rm -rf *.egg-info
    find . -type d -name "__pycache__" -exec rm -rf {} +