set dotenv-load := true

install:
    uv sync

dev:
    uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

format:
    ruff format .

lint:
    ruff check .

clean:
    rm -rf dist
    rm -rf *.egg-info
    find . -type d -name "__pycache__" -exec rm -rf {} +

gen:
    uv run python -m scripts.schema

db-push:
    uv run alembic upgrade head