/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI Backend
 * Backend API for FastAPI-Tanstack project
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProductResponseDescription } from "./createProductResponseDescription";

export interface CreateProductResponse {
  id: string;
  name: string;
  description?: CreateProductResponseDescription;
  price: number;
}
