/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI Backend
 * Backend API for FastAPI-Tanstack project
 * OpenAPI spec version: 1.0.0
 */

export type ListProductsV1ProductsGetParams = {
  page?: number;
  page_size?: number;
};
