/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI Backend
 * Backend API for FastAPI-Tanstack project
 * OpenAPI spec version: 1.0.0
 */
import type { ProductInfo } from "./productInfo";

export interface ListProductsResponse {
  total: number;
  page: number;
  page_size: number;
  products: ProductInfo[];
}
