/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI Backend
 * Backend API for FastAPI-Tanstack project
 * OpenAPI spec version: 1.0.0
 */
import type { ProductInfoDescription } from "./productInfoDescription";

export interface ProductInfo {
  id: string;
  name: string;
  description?: ProductInfoDescription;
  price: number;
}
