"""Make description non-optional

Revision ID: 855f2864e24b
Revises: a745d8867235
Create Date: 2025-06-24 18:42:24.135401

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "855f2864e24b"
down_revision: Union[str, Sequence[str], None] = "a745d8867235"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE products SET description = '' WHERE description IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
