/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI Backend
 * Backend API for FastAPI-Tanstack project
 * OpenAPI spec version: 1.0.0
 */
import type { Product } from "./product";

export interface ListProductsResponse {
  products: Product[];
  total: number;
  page: number;
  page_size: number;
}
