name: Frontend Code linting

on:
  pull_request:
    branches: ["**"]
    paths:
      - ".github/workflows/frontend.yml"
      - "frontend/**"

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Check lockfile consistency
        run: bun install --frozen-lockfile
      - name: Run linter
        run: bun run lint
      - name: Run formatter
        run: bun run format:check
